name: "sj430842"
services:
  service1:
    build: ./service1/
    environment:
      - TARGET_PORT=8000
      - TARGET_HOST=service2
    depends_on:
      rabbitmq:
        condition: service_healthy
      monitor: 
        # So that logs are listened to
        condition: service_started
  service2:
    build: ./service2/
    depends_on:
      rabbitmq:
        condition: service_healthy
      monitor: 
        # So that logs are listened to
        condition: service_started
  monitor:
    build: ./monitor
    depends_on:
      rabbitmq:
        condition: service_healthy
  api-gateway:
    build: ./api_gateway
    ports:
      - 8083:8083
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3.12.7-alpine
    # A health check is used to see if rabbitmq is ready before starting other containers
    # In a real world case the interval would be longer, but due to the timing requirements of this task it is set to 5 seconds
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 5s
      timeout: 5s
      retries: 10